version: "3.9"
services:
    app:
        build:
            context: .
        ports: 
            - 3000-3005:3000-3005
        environment: 
            - PORT=3003
        volumes: 
            - ./dist:/app/dist
            - ./src:/app/src
            - filesBeat:/app/node_modules
        entrypoint: ["tail", "-f", "/dev/null"]
volumes: 
    filesBeat:
