apiVersion: apps/v1
kind: Deployment
metadata: 
  name: echo-deployment
spec: 
  selector:
    matchLabels:
      app: echo
  replicas: 3
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo-server
        image: luyi985/echo-server:latest
        ports:
        - containerPort: 80

    
